Select
  PREVISAO.Produto AS Produto,
  PREVISAO.ANO_PREVISAO AS ANO_PREVISAO,
  PREVISAO.QUANT_PREVISTA AS QUANT_PREVISTA,
  PREVISAO.VALOR_PREVISTO AS VALOR_PREVISTO,
  PREVISAO.Usuario AS Usuario
from PREVISAO
Order By PREVISAO.Produto,PREVISAO.ANO_PREVISAO
