Select
  USER_MENU_LATERAL.Opcao AS Opcao,
  USER_MENU_LATERAL.Grupo AS Grupo,
  USER_MENU_LATERAL.PorSenha AS PorSenha
from USER_MENU_LATERAL
Order By USER_MENU_LATERAL.Opcao,USER_MENU_LATERAL.Grupo
