Select
  USER_MENU_SUPERIOR.Opcao AS Opcao,
  USER_MENU_SUPERIOR.Grupo AS Grupo,
  USER_MENU_SUPERIOR.PorSenha AS PorSenha,
  USER_MENU_SUPERIOR.Invisivel AS Invisivel
from USER_MENU_SUPERIOR
Order By USER_MENU_SUPERIOR.Opcao,USER_MENU_SUPERIOR.Grupo
