{
 Classe de tabelas
}

DBoocking, DClientes, DContratoTransporte, DDIVISOES, DExpotadoTransito, DFatura, DFornecedores, DPARAMETROS, DProdutos, 
DPrudutoContratoT, DTAB_PAIS, DTbAtividades, DTbCategClientes, DTbCondicaoCompra, DTbFormaPagamento, DTbPorto, DTbSitClientes, 
DUSER_AGENDA, DUSER_BARRA_F, DUSER_GRUPOS, DUSER_LOG, DUSER_MENU_LATERAL, DUSER_MENU_SUPERIOR, DUSER_NOMES, DUSER_TABELAS, 
CSCNS_Infome, 

