{
 Classe de tabelas
}

DBoocking, DCERBO, DClientes, DContratoTransporte, DDivisoes, DExportadoTransito, DFatura, DFornecedores, DInforme, 
DOrdemCobranca, DOrdemCobrancaDescont, DOrdemCobrancaProdExp, DPREVISAO, DParametros, DProdutoContratoT, DProdutos, DRESUMENCONTRATACION, 
DSituacao, DTab_pais, DTbAtividades, DTbCategClientes, DTbCondicaoCompra, DTbFormaPagamento, DTbPorto, DTbSitClientes, 
DUSER_AGENDA, DUSER_BARRA_F, DUSER_GRUPOS, DUSER_LOG, DUSER_MENU_LATERAL, DUSER_MENU_SUPERIOR, DUSER_NOMES, DUSER_TABELAS, 
CSInfome, 

